# 服务名称
spring:
  application:
    name: hengboy-spring-cloud-eureka-production
  devtools: 
    restart: 
      enabled: true
  datasource:
    url: jdbc:mysql://localhost/hibernate3?characterEncoding=utf-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true
        dialect: cn.wk.springcloud.dialect.MySQL5DialectUTF8
# 服务端口号
server:
  port: 8003
  
#Eureka 相关配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka02.com:7002/eureka/,http://eureka03.com:7003/eureka/,http://eureka01.com:7001/eureka/
    instance:
      prefer-ip-address: true
