# 服务名称
spring:
  application:
    name: hengboy-spring-cloud-eureka-server
# 服务端口号
server:
  port: 7001
  
spring.devtools.restart.enabled: true

#Eureka 相关配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka02.com:7002/eureka/,http://eureka03.com:7003/eureka/
    # 是否从其他的服务中心同步服务列表
    fetch-registry: true
    # 是否把自己作为服务注册到其他服务注册中心
    register-with-eureka: true
  instance: 
    hostname: eureka-server-7001