server: 
  port: 3344 
  
spring:
  application:
    name:  springcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/15249684972/springcloud-config.git #GitHub上面的git仓库名字
          username: 15249684972
          password: wangkunn123